Select * from customer




--1. **What is the total revenue generated by male vs. female customers?**

Select gender,
Round(Sum(purchase_amount_usd)/(Select Sum(purchase_amount_usd) From customer)*100,0) as per_revenue
from customer
Group by gender



--2. **Which customers used a discount but still spent more than or equal to the average purchase amount?**

SELECT customer_id, purchase_amount_usd
FROM customer
WHERE discount_applied = 'Yes' 
  AND purchase_amount_usd >= (SELECT AVG(purchase_amount_usd) FROM customer);


--3. **What are the top 5 products with the highest average review rating?**
Select top 5 
from customer


--4. **How does the average purchase amount compare between Standard and Express shipping?**
--5. **Do subscribed customers spend more? What is the breakdown of average spend and total revenue between subscribers and non-subscribers?**
--6. **Which 5 products have the highest percentage of purchases made with a discount?**
--7. **How many customers fall into each segment when categorized as New, Returning, or Loyal based on their previous purchase count?**
--8. **What are the top 3 most purchased products within each category?**
--9. **Are repeat buyers (customers with more than 5 previous purchases) likely to have an active subscription?**
--10. **What is the total revenue contribution generated by each age group?**